@url = http://localhost:3333/api/v1/communities

POST {{url}}
Content-Type: application/json

{
	"name": "Khodar",
  "email": "hello9@khodar.co.mz",
  "password": "123456"
}

###

GET {{url}}?name=Kho

###

GET  {{url}}/0c5c6ef2-8de3-4687-ad18-045c09d053cb

###

PUT  {{url}}/

{
	"communityId": "0c5c6ef2-8de3-4687-ad18-045c09d053cb",
	"name": "Khodar edited",
	"description": "A comunidade dos devs Full Stack de moz",
  "email": "helloedit@khodar.co.mz",
	"website": "khodar.co.mz"
}

###

PATCH {{url}}/verify/d4bf840d-3629-4662-a15b-1af6ea1725dd

{

}


###

PATCH {{url}}/reset-password/59e3bcba-7482-4a91-a994-ccd096184992

{
	"password": "password"
}



###

GET  {{url}}/events

###

GET  {{url}}/me

###

PATCH {{url}}/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="communityId"

0c5c6ef2-8de3-4687-ad18-045c09d053cb
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="khodar.jpg"
Content-Type: image/jpeg

< ./images/khodar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
