@url = http://localhost:3333/api/v1/events

POST {{url}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Khodar 1ª edição
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

1ª edição do melhor treinamento para devs
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="limit"

30
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="date"

2024-01-15
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

PUBLISHED
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="startTime"

08:00
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="endTime"

11:00
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="banner"; filename="khodar.jpg"
Content-Type: image/jpeg

< ./images/khodar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET {{url}}?title=edição&communityId=0f2217d2-81b9-4d00-b68c-b349bf8a5e90
Content-Type: application/json

###

GET {{url}}/28bba7ac-dd09-411f-a2be-00d738af82d0

###

DELETE {{url}}/28bba7ac-dd09-411f-a2be-00d738af82d0
