@url = http://localhost:3333/api/v1/sessions

POST {{url}}
Content-Type: application/json

{
	"email": "hello8@khodar.co.mz",
	"password": "password"
}

###

DELETE {{url}}

###

PATCH {{url}}/reset-password

{
	"email": "hello8@khodar.co.mz"
}
